<?php
/**
 * Created by IntelliJ IDEA.
 * User: richardmiles
 * Date: 2/7/19
 * Time: 1:58 AM
 */

namespace Tests\Browser;



use PHPUnit\Extensions\Selenium2TestCase;

/** Selenium2TestCase
 * @link https://github.com/giorgiosironi/phpunit-selenium/blob/master/Tests/Selenium2TestCaseTest.php
 * @link http://apigen.juzna.cz/doc/sebastianbergmann/phpunit-selenium/class-PHPUnit_Extensions_Selenium2TestCase.html
 */
class NavigationTest extends Selenium2TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setDesiredCapabilities([
            'chromeOptions' => [
                'w3c' => false
            ]
        ]);

        $this->setBrowserUrl('http://127.0.0.1:8080/');

        $this->setHost('localhost');

        $this->setPort(4444);

        $this->setBrowser('chrome');

        $this->prepareSession()->currentWindow()->maximize();

        $this->setSeleniumServerRequestsTimeout(10);

        $this->url('/');

    }


    public function testBasicNavigation(): void
    {

        if (!defined('DS')) {

            define('DS', DIRECTORY_SEPARATOR);

        }

        //self::$ROOT_DIRECTORY = dirname(__DIR__) . DS;

        //self::startSeleniumServer();

        self::shareSession(true);



        $register = $this->byId('staticSite');

        self::assertEquals('port 3000', $register->text());

        #
        #self::assertEquals('', $this->title());

      /*  $this->timeouts()->implicitWait(10000);//10 seconds

        $register = $this->byId('register');

        self::assertEquals('Register a new membership', $register->text());

        $link = $this->byLinkText('Register a new membership');

        $link->click(); // we must grab all new elements now

        $this->timeouts()->implicitWait(10000);//10 seconds*/

    }

}
