<?php

declare(strict_types=1);

// Parent of Model class, can only be called indirectly

namespace CarbonPHP\Classes;

use CarbonPHP\Abstracts\ColorCode;
use CarbonPHP\CarbonPHP;
use CarbonPHP\Interfaces\iColorCode;
use CarbonPHP\Abstracts\Restful\RestfulValidations;
use CarbonPHP\Interfaces\iDatabasePool;
use CarbonPHP\Throwables\PrivateAlert;
use PDO;
use PDOException;
use stdClass;
use Throwable;
use function count;

/**
 * Class Database
 *
 * @see https://en.wikipedia.org/wiki/Entity–component–system
 */
abstract class Database extends RestfulValidations implements iDatabasePool
{
    /** the database method will return a connection to the database.
     * Before returning a connection it must pass an active check.
     * This is mainly for persistent socket connections.
     *
     * @param bool $reader
     *
     * @return PDO
     */
    public function database(bool $reader): PDO
    {
        $databaseConfiguration = $this->searchConfigurations($reader);

        if (null === $databaseConfiguration->database) { // todo - can we get the ini of mysql timeout?
            return $databaseConfiguration->reset();
        }

        $oldLevel = error_reporting(0);
        $database = $databaseConfiguration->database;

        try {
            // this has a lot of waist at this point
            $database->prepare('SELECT 1')->execute();
            error_reporting($oldLevel);

            return $database;
        } catch (PDOException $e) {
            ColorCode::colorCode('PDOException '.get_class($e).' '.$e->getMessage(), iColorCode::BACKGROUND_YELLOW);
            ColorCode::colorCode($e->getTraceAsString(), iColorCode::YELLOW);

            return $databaseConfiguration->reset();
        } catch (Throwable $e) {
            ThrowableHandler::generateLog($e, true);
            ColorCode::colorCode('Attempting to reset the database. Possible disconnect.', iColorCode::BACKGROUND_YELLOW);
            error_reporting($oldLevel);

            return $databaseConfiguration->reset();
        }
    }

    public function setUp(bool $refresh = true, bool $cli = CarbonPHP::CLI): PDO
    {
        $writerDatabase = $this->searchConfigurations(false);

        if ($cli) {
            ColorCode::colorCode('This build is automatically generated by CarbonPHP. When you add a table be sure to re-execute the RestBuilder.', iColorCode::BACKGROUND_CYAN);
            ColorCode::colorCode('Connecting on '.$writerDatabase->carbonDatabaseDSN);
        } else {
            echo '<h3>This build is automatically generated by CarbonPHP. When you add a table be sure to re-execute the <br><br><br><b>>> php index.php restbuilder</b></h3>'
                .'<h1>Connecting on </h1>' . $writerDatabase->carbonDatabaseDSN . '<br>';
        }

        self::refreshDatabase();

        if ($refresh && !$cli) {
            echo '<br><br><h2>Refreshing in 6 seconds</h2><script>let t1 = window.setTimeout(function(){ window.location.href = \''.CarbonPHP::$site.'\'; },6000);</script>';
            exit(0);
        }

        return static::database(false);
    }

    public function execute(string $sql, ...$execute): bool
    {
        $reader = false === self::isWriteQuery($sql);

        return $this->database($reader)->prepare($sql)->execute($execute);
    }

    public function fetchAll(string $sql, ...$execute): false|array
    {
        try {
            $reader = false === self::isWriteQuery($sql);

            $stmt = $this->database($reader)->prepare($sql);

            if (false === $stmt->execute($execute)) {
                throw new PrivateAlert("Failed to execute query ($sql).");
            }

            return $stmt->fetchAll(PDO::FETCH_ASSOC);   // promise this is needed and will still return the desired array
        } catch (Throwable $e) {
            ThrowableHandler::generateLogAndExit($e);  // this terminates
        }
    }

    public function fetchAllCustom(string $sql, int $fetchMode = PDO::FETCH_ASSOC, ...$execute): array|false
    {
        try {
            $reader = false === self::isWriteQuery($sql);
            $stmt   = $this->database($reader)->prepare($sql);

            if (false === $stmt->execute($execute)) {
                throw new PrivateAlert("Failed to execute query ($sql).");
            }

            return $stmt->fetchAll($fetchMode);   // promise this is needed and will still return the desired array
        } catch (Throwable $e) {
            ThrowableHandler::generateLog($e);  // this terminates
            exit(112);
        }
    }

    /** Quickly prepare and execute PDO $sql statements using
     * @NOTE PDO's version of fetchColumn() will fail on statements like SHOW TABLES;
     *
     * @TODO can we optimise based on when we know it will fail?
     *  variable arguments.
     *
     * Example:
     * $array['following'] = self::fetchColumn('SELECT follows_user_id FROM user_followers WHERE user_id = ?', $id);
     *
     * @param string $sql - variables should be denoted by question marks
     * @param ...$execute -
     *                   if multiple question marks exist you may use comma separated parameters to fill the statement
     *
     * @return array
     */
    public function fetchColumn(string $sql, ...$execute): array
    {
        $reader = false === self::isWriteQuery($sql);

        $stmt = $this->database($reader)->prepare($sql);

        if (!$stmt->execute($execute)) {
            return [];
        }

        // pdo's version of fetchColumn is flawed see note
        $count = count($stmt = $stmt->fetchAll(PDO::FETCH_ASSOC));

        if ($count === 0) {
            return $stmt;
        }

        if ($count === 1) {
            while (\is_array($stmt)) {
                $stmt = \array_shift($stmt);
            }

            return [$stmt];
        }

        foreach ($stmt as &$value) {
            while (\is_array($value)) {
                $value = \array_shift($value);
            }
        }

        return $stmt;
    }

    /**
     * This returns all values from the requested query as an Object to type stdClass.
     *  Its important to note that PHP arrays are hash tables. This means that
     *  while semantically pleasing, fetching into an object should be avoided
     */
    protected function fetch_object(string $sql, ...$execute): mixed
    {
        $reader = false === self::isWriteQuery($sql);

        $stmt = $this->database($reader)->prepare($sql);

        $stmt->setFetchMode(PDO::FETCH_CLASS, \stdClass::class);

        if (!$stmt->execute($execute)) {
            throw new \RuntimeException('Failed to Execute');
        }

        $stmt = $stmt->fetchAll();  // user obj

        return count($stmt) === 1 ? $stmt[0] : $stmt;
    }

    /** Each row received will be converted into its own object
     * @param string $sql
     * @param array ...$execute
     *
     * @return array of stdClass::class objects
     */
    protected function fetch_classes(string $sql, ...$execute): array
    {
        $reader = false === self::isWriteQuery($sql);

        $stmt = $this->database($reader)->prepare($sql);

        $stmt->setFetchMode(PDO::FETCH_CLASS, \stdClass::class);

        if (!$stmt->execute($execute)) {
            return [];
        }

        return $stmt->fetchAll();  // user obj
    }

    protected function fetch_into_class(&$object, $sql, ...$execute): void
    {
        $reader = false === self::isWriteQuery($sql);

        $stmt = $this->database($reader)->prepare($sql);

        $stmt->execute($execute);

        $array = $stmt->fetchAll(PDO::FETCH_ASSOC);

        foreach ($array as $key => $value) {
            $object->$key = $value;
        }
    }

    /**
     * Determine the likelihood that this query could alter anything
     * Statements are considered read-only when:
     * 1. not including UPDATE nor other "may-be-write" strings
     * 2. begin with SELECT etc.
     *
     * @param string $q query
     * @return bool
     * @since 1.0.0
     * @source /ludicrousdb/includes/class-ludicrousdb.php
     */
    public static function isWriteQuery(string $q = ''): bool
    {
        // Trim potential whitespace or subquery chars
        $q = ltrim($q, "\r\n\t (");

        // Possible writes
        if (preg_match('/(?:^|\s)(?:ALTER|CREATE|ANALYZE|CHECK|OPTIMIZE|REPAIR|CALL|DELETE|DROP|INSERT|LOAD|REPLACE|UPDATE|SHARE|SET|RENAME\s+TABLE)(?:\s|$)/i', $q)) {
            return true;
        }

        // Not possible non-writes (phew!)
        return !preg_match('/^(?:SELECT|SHOW|DESCRIBE|DESC|EXPLAIN)(?:\s|$)/i', $q);
    }

    // todo - think this over and implement
    private function getLeastBusyWriteHost($hosts)
    {
        foreach ($hosts as $host) {
            $pdo    = new PDO("mysql:host=$host;dbname=app", 'user', 'password');
            $stmt   = $pdo->query("SHOW STATUS LIKE 'Threads_connected'");
            $result = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($result['Value'] < 50) { // If fewer than 50 active connections
                return $host;
            }
        }

        return $hosts[0]; // Default to first host
    }
}
