<?php /** @noinspection DuplicatedCode */

namespace CarbonPHP\Tables;

// Restful defaults
use CarbonPHP\Database;
use CarbonPHP\Error\PublicAlert;
use CarbonPHP\Interfaces\iRestSinglePrimaryKey;
use CarbonPHP\Helpers\RestfulValidations;
use CarbonPHP\Rest;
use JsonException;
use PDO;
use PDOException;
use function array_key_exists;
use function count;
use function func_get_args;
use function is_array;

// Custom User Imports


/**
 *
 * Class Wp_Posts
 * @package CarbonPHP\Tables
 * @note Note for convenience, a flag '-prefix' maybe passed to remove table prefixes.
 *  Use '-help' for a full list of options.
 * @link https://carbonphp.com/ 
 *
 * This class contains autogenerated code.
 * This class is a 1=1 relation named after a table in the database schema provided to the program `RestBuilder`.
 * Your edits are preserved during updates given they follow::
 *      METHODS SHOULD ONLY BE STATIC and may be reordered during generation.
 *      FUNCTIONS MUST NOT EXIST outside the class. (methods and functions are not the same.)
 *      IMPORTED CLASSED AND FUNCTIONS ARE ALLOWED though maybe reordered.
 *      ADDITIONAL CONSTANTS of any kind ARE NOT ALLOWED.
 *      ADDITIONAL CLASS MEMBER VARIABLES are NOT ALLOWED.
 *
 * When creating static member functions which require persistent variables, consider making them static members of that 
 *  static method.
 */
class Wp_Posts extends Rest implements iRestSinglePrimaryKey
{
    use RestfulValidations;
    
    public const CLASS_NAME = 'Wp_Posts';
    public const CLASS_NAMESPACE = 'CarbonPHP\Tables\\';
    public const TABLE_NAME = 'wp_posts';
    public const TABLE_PREFIX = '';
    
    /**
     * COLUMNS
     * The columns below are a 1=1 mapping to the columns found in wp_posts. 
     * Changes, shuch as adding or removing a column, SHOULD be made first in the database. The RestBuilder program will 
     * capture any changes made in MySQL and update this file auto-magically. 
    **/
    public const ID = 'wp_posts.ID'; 

    public const POST_AUTHOR = 'wp_posts.post_author'; 

    public const POST_DATE = 'wp_posts.post_date'; 

    public const POST_DATE_GMT = 'wp_posts.post_date_gmt'; 

    public const POST_CONTENT = 'wp_posts.post_content'; 

    public const POST_TITLE = 'wp_posts.post_title'; 

    public const POST_EXCERPT = 'wp_posts.post_excerpt'; 

    public const POST_STATUS = 'wp_posts.post_status'; 

    public const COMMENT_STATUS = 'wp_posts.comment_status'; 

    public const PING_STATUS = 'wp_posts.ping_status'; 

    public const POST_PASSWORD = 'wp_posts.post_password'; 

    public const POST_NAME = 'wp_posts.post_name'; 

    public const TO_PING = 'wp_posts.to_ping'; 

    public const PINGED = 'wp_posts.pinged'; 

    public const POST_MODIFIED = 'wp_posts.post_modified'; 

    public const POST_MODIFIED_GMT = 'wp_posts.post_modified_gmt'; 

    public const POST_CONTENT_FILTERED = 'wp_posts.post_content_filtered'; 

    public const POST_PARENT = 'wp_posts.post_parent'; 

    public const GUID = 'wp_posts.guid'; 

    public const MENU_ORDER = 'wp_posts.menu_order'; 

    public const POST_TYPE = 'wp_posts.post_type'; 

    public const POST_MIME_TYPE = 'wp_posts.post_mime_type'; 

    public const COMMENT_COUNT = 'wp_posts.comment_count'; 

    /**
     * PRIMARY
     * This could be null for tables without primary key(s), a string for tables with a single primary key, or an array 
     * given composite primary keys. The existence and amount of primary keys of the will also determine the interface 
     * aka method signatures used.
    **/
    public const PRIMARY = 'wp_posts.ID';

    /**
     * COLUMNS
     * This is a convience constant for accessing your data after it has be returned from a rest operation. It is needed
     * as Mysql will strip away the tablename we have explicitly provided to each column (to help with join statments).
     * Thus, accessing your return values might look something like:
     *      $return[self::COLUMNS[self::EXAMPLE_COLUMN_ONE]]
    **/ 
    public const COLUMNS = [
        'wp_posts.ID' => 'ID','wp_posts.post_author' => 'post_author','wp_posts.post_date' => 'post_date','wp_posts.post_date_gmt' => 'post_date_gmt','wp_posts.post_content' => 'post_content','wp_posts.post_title' => 'post_title','wp_posts.post_excerpt' => 'post_excerpt','wp_posts.post_status' => 'post_status','wp_posts.comment_status' => 'comment_status','wp_posts.ping_status' => 'ping_status','wp_posts.post_password' => 'post_password','wp_posts.post_name' => 'post_name','wp_posts.to_ping' => 'to_ping','wp_posts.pinged' => 'pinged','wp_posts.post_modified' => 'post_modified','wp_posts.post_modified_gmt' => 'post_modified_gmt','wp_posts.post_content_filtered' => 'post_content_filtered','wp_posts.post_parent' => 'post_parent','wp_posts.guid' => 'guid','wp_posts.menu_order' => 'menu_order','wp_posts.post_type' => 'post_type','wp_posts.post_mime_type' => 'post_mime_type','wp_posts.comment_count' => 'comment_count',
    ];

    public const PDO_VALIDATION = [
        'wp_posts.ID' => ['bigint', 'PDO::PARAM_INT', ''],'wp_posts.post_author' => ['bigint', 'PDO::PARAM_INT', ''],'wp_posts.post_date' => ['datetime', 'PDO::PARAM_STR', ''],'wp_posts.post_date_gmt' => ['datetime', 'PDO::PARAM_STR', ''],'wp_posts.post_content' => ['longtext', 'PDO::PARAM_STR', ''],'wp_posts.post_title' => ['text', 'PDO::PARAM_STR', ''],'wp_posts.post_excerpt' => ['text', 'PDO::PARAM_STR', ''],'wp_posts.post_status' => ['varchar', 'PDO::PARAM_STR', '20'],'wp_posts.comment_status' => ['varchar', 'PDO::PARAM_STR', '20'],'wp_posts.ping_status' => ['varchar', 'PDO::PARAM_STR', '20'],'wp_posts.post_password' => ['varchar', 'PDO::PARAM_STR', '255'],'wp_posts.post_name' => ['varchar', 'PDO::PARAM_STR', '200'],'wp_posts.to_ping' => ['text', 'PDO::PARAM_STR', ''],'wp_posts.pinged' => ['text', 'PDO::PARAM_STR', ''],'wp_posts.post_modified' => ['datetime', 'PDO::PARAM_STR', ''],'wp_posts.post_modified_gmt' => ['datetime', 'PDO::PARAM_STR', ''],'wp_posts.post_content_filtered' => ['longtext', 'PDO::PARAM_STR', ''],'wp_posts.post_parent' => ['bigint', 'PDO::PARAM_INT', ''],'wp_posts.guid' => ['varchar', 'PDO::PARAM_STR', '255'],'wp_posts.menu_order' => ['int', 'PDO::PARAM_INT', ''],'wp_posts.post_type' => ['varchar', 'PDO::PARAM_STR', '20'],'wp_posts.post_mime_type' => ['varchar', 'PDO::PARAM_STR', '100'],'wp_posts.comment_count' => ['bigint', 'PDO::PARAM_INT', ''],
    ];
     
    /**
     * REFRESH_SCHEMA
     * These directives should be designed to maintain and update your team's schema &| database &| table over time. 
     * It is RECOMMENDED that ALL changes you make in your local env be programmatically coded out in callables such as 
     * the 'tableExistsOrExecuteSQL' method call below. If a PDO exception is thrown with `$e->getCode()` equal to 42S02 
     * or 1049 CarbonPHP will attempt to REFRESH the full database with with all directives in all tables. If possible 
     * keep table specific procedures in it's respective restful-class table file. Check out the 'tableExistsOrExecuteSQL' 
     * method in the parent class to see a more abstract procedure.
     * Each directive MUST be designed to run multiple times without failure.
     */
    public const REFRESH_SCHEMA = [
        [self::class => 'tableExistsOrExecuteSQL', self::TABLE_NAME, self::REMOVE_MYSQL_FOREIGN_KEY_CHECKS .
                        PHP_EOL . self::CREATE_TABLE_SQL . PHP_EOL . self::REVERT_MYSQL_FOREIGN_KEY_CHECKS]
    ]; 
    
    /**
     * REGEX_VALIDATION
     * Regular Expression validations will run before and recommended over PHP_VALIDATION.
     * It is a 1 to 1 column regex relation with fully regex for preg_match_all(). This regex must satisfy the condition 
     *        1 > preg_match_all(self::$compiled_regex_validations[$column], $value, ...
     * 
     * Table generated column constants must be used. 
     *       self::EXAMPLE_COLUMN_NAME => '#^[A-F0-9]{20,35}$#i'
     *
     * @link https://regexr.com
     * @link https://php.net/manual/en/function.preg-match-all.php
     */
    public const REGEX_VALIDATION = []; 
     
     
    /**
     * PHP_VALIDATION
     * PHP validations works as follows:
     * @note regex validation is always step #1 and should be favored over php validations.
     *  Syntax ::
     *      [Example_Class::class => 'disallowPublicAccess', (optional) ...$rest]
     *      self::EXAMPLE_COLUMN => [Example_Class::class => 'exampleOtherMethod', (optional) ...$rest]
     *
     *  Callables defined above MUST NOT RETURN FALSE. Moreover; return values are ignored so `): void {` may be used. 
     *  array_key_first() must return a fully qualified class namespace. In the example above Example_Class would be a
     *  class defined in our system. PHP's `::class` appended to the end will return the fully qualified namespace. Note
     *  this will require the custom import added to the top of the file. You can allow your editor to add these for you
     *  as the RestBuilder program will capture, preserve, and possibly reorder the imports. The value of the first key 
     *  MUST BE the exact name of a member-method of that class. Typically validations are defined in the same class 
     *  they are used ('self::class') though it is useful to export more dynamic functions. The $rest variable can be 
     *  used to add additional arguments to the request. RESTFUL INTERNAL ARGUMENTS will be passed before any use defined
     *  variables after the first key value pair. Only array values will be passed to the method. Thus, additional keys 
     *  listed in the array will be ignored. Take for example::
     *
     *      [ self::class => 'validateUnique', self::class, self::EXAMPLE_COLUMN]
     *  The above is defined in RestfulValidations::class. 
     *      RestfulValidations::validateUnique(string $columnValue, string $className, string $columnName)
     *  Its definition is with a trait this classes inherits using `use` just after the `class` keyword. 
     * 
     *   What is the RESTFUL lifecycle?
     *      Regex validations are done first on any main query; sub-queries are treated like callbacks which get run 
     *      during the main queries invocation. The main query is 'paused' while the sub-query will compile and validate.
     *      Validations across tables are concatenated on joins and sub-queries. All callbacks will be run across any 
     *       table joins.
     *      
     *   What are the RESTFUL INTERNAL ARGUMENTS? (The single $arg string or array passed before my own...)
     *      REST_REQUEST_PREPROCESS_CALLBACKS ::   
     *           PREPROCESS::
     *              Methods defined here will be called at the beginning of every request. 
     *              Each method will be passed ( & self::$REST_REQUEST_PARAMETERS ) by reference so changes can be made pre-request.
     *              Method validations under the main 'PREPROCESS' key will be run first, while validations specific to 
     *              ( GET | POST | PUT | DELETE )::PREPROCESS will be run directly after.
     *
     *           FINAL:: 
     *              Each method will be passed the final ( & $SQL ), which may be a sub-query, by reference.
     *              Modifying the SQL string will effect the parent function. This can have disastrous effects.
     *
     *           COLUMN::
     *              Preformed while a column is being parsed in a query. The first column validations to run.
     *              Each column specific method under PREPROCESS will be passed nothing from rest. 
     *              Each method will ONLY be RUN ONCE regardless of how many times the column has been seen. 
     *
     *      COLUMN::
     *           Column validations are only run when they have been parsed in the query. Global column validations maybe
     *            RUN MULTIPLE TIMES if the column is used multiple times in a single restful query. 
     *           If you have a column that is used multiple times the validations will run for each occurrence.
     *           Column validation can mean many thing. There are three possible scenarios in which your method 
     *            signature would change. For this reason it is more common to use method ( GET | POST ... ) wise column validations.
     *              *The signature required are as follows:
     *                  Should the column be...
     *                      SELECTED:  
     *                          In a select stmt no additional parameters will be passed.
     *                      
     *                      ORDERED BY: (self::ASC | self::DESC)
     *                          The $operator will be passed to the method.
     *  
     *                      JOIN STMT:
     *                          The $operator followed by the $value will be passed. 
     *                          The operator could be :: >,<,<=,<,=,<>,=,<=>
     *
     *      REST_REQUEST_FINNISH_CALLBACKS::
     *          PREPROCESS::
     *              These callbacks are called after a successful PDOStatement->execute() but before Database::commit().
     *              Each method will be passed ( GET => &$return, DELETE => &$remove, PUT => &$returnUpdated ) by reference. 
     *              POST will BE PASSED NULL.          
     *
     *          FINAL::
     *              Run directly after method specific [FINAL] callbacks.
     *              The final, 'final' callback set. After these run rest will return. 
     *              Each method will be passed ( GET => &$return, DELETE => &$remove, PUT => &$returnUpdated ) by reference. 
     *              POST will BE PASSED NULL. 
     *
     *          COLUMN::
     *              These callables will be run after the [( GET | POST | PUT | DELETE )][FINAL] methods.
     *              Directly after, the [REST_REQUEST_FINNISH_CALLBACKS][FINAL] will run. 
     *              
     *
     *      (POST|GET|PUT|DELETE)::
     *          PREPROCESS::
     *              Methods run after any root 'REST_REQUEST_PREPROCESS_CALLBACKS'
     *              Each method will not be passed any argument from system. User arguments will be directly reflected.
     *
     *          COLUMN::
     *              Methods run after any root column validations, the last of the PREPROCESS column validations to run.
     *              Based on the existences and number of primary key(s), the signature will change. 
     *               See the notes on the base column validations as signature of parameters may change. 
     *              It is not possible to directly define a method->column specific post processes. This can be done by
     *               dynamically pairing multiple method processes starting with one here which signals a code routine 
     *               in a `finial`-ly defined method. The FINAL block specific to the method would suffice. 
     *
     *          FINAL::
     *              Passed the ( & $return )  
     *              Run before any other column validation 
     *
     *  Be aware the const: self::DISALLOW_PUBLIC_ACCESS = [self::class => 'disallowPublicAccess'];
     *  could be used to replace each occurrence of 
     *          [self::class => 'disallowPublicAccess', self::class]
     *  though would loose information as self::class is a dynamic variable which must be used in this class given 
     *  static and constant context. 
     *  @version ^9
     */
 
    public const PHP_VALIDATION = [ 
        self::REST_REQUEST_PREPROCESS_CALLBACKS => [ 
            self::PREPROCESS => [ 
                [self::class => 'disallowPublicAccess', self::class],
            ]
        ],
        self::GET => [ 
            self::PREPROCESS => [ 
                [self::class => 'disallowPublicAccess', self::class],
            ]
        ],    
        self::POST => [ self::PREPROCESS => [[ self::class => 'disallowPublicAccess', self::class ]]],    
        self::PUT => [ self::PREPROCESS => [[ self::class => 'disallowPublicAccess', self::class ]]],    
        self::DELETE => [ self::PREPROCESS => [[ self::class => 'disallowPublicAccess', self::class ]]],
        self::REST_REQUEST_FINNISH_CALLBACKS => [ self::PREPROCESS => [[ self::class => 'disallowPublicAccess', self::class ]]]    
    ]; 
   
    /**
     * CREATE_TABLE_SQL is autogenerated and should not be manually updated. Make changes in MySQL and regenerate using
     * the RestBuilder program.
     */
    public const CREATE_TABLE_SQL = /** @lang MySQL */ <<<MYSQL
    CREATE TABLE `wp_posts` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `post_author` bigint unsigned NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_title` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_excerpt` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open',
  `post_password` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `post_name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `to_ping` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `pinged` text COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `post_parent` bigint unsigned NOT NULL DEFAULT '0',
  `guid` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `menu_order` int NOT NULL DEFAULT '0',
  `post_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `comment_count` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `post_name` (`post_name`(191)),
  KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  KEY `post_parent` (`post_parent`),
  KEY `post_author` (`post_author`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
MYSQL;
   
   

    
    /**
     * @deprecated Use the class constant CREATE_TABLE_SQL directly
     * @return string
     */
    public static function createTableSQL() : string {
        return self::CREATE_TABLE_SQL;
    }
    
    /**
    * Currently nested aggregation is not supported. It is recommended to avoid using 'AS' where possible. Sub-selects are 
    * allowed and do support 'as' aggregation. Refer to the static subSelect method parameters in the parent `Rest` class.
    * All supported aggregation is listed in the example below. Note while the WHERE and JOIN members are syntactically 
    * similar, and are moreover compiled through the same method, our aggregation is not. Please refer to this example 
    * when building your queries. By design, queries using subSelect are only allowed internally. Public Sub-Selects may 
    * be given an optional argument with future releases but will never default to on. Thus, you external API validation
    * need only validate for possible table joins. In many cases sub-selects can be replaces using simple joins, this is
    * highly recommended.
    *
    *   $argv = [
    *       Rest::SELECT => [
    *              'table_name.column_name',                            // bad, dont pass strings manually. Use Table Constants instead.
    *              self::EXAMPLE_COLUMN_ONE,                            // good, 
    *              [self::EXAMPLE_COLUMN_TWO, Rest::AS, 'customName'],
    *              [Rest::COUNT, self::EXAMPLE_COLUMN_TWO, 'custom_return_name_using_as'],
    *              [Rest::GROUP_CONCAT, self::EXAMPLE_COLUMN_THREE], 
    *              [Rest::MAX, self::EXAMPLE_COLUMN_FOUR], 
    *              [Rest::MIN, self::EXAMPLE_COLUMN_FIVE], 
    *              [Rest::SUM, self::EXAMPLE_COLUMN_SIX], 
    *              [Rest::DISTINCT, self::EXAMPLE_COLUMN_SEVEN], 
    *              ANOTHER_EXAMPLE_TABLE::subSelect($primary, $argv, $as, $pdo, $database)
    *       ],
    *       Rest::WHERE => [
    *              
    *              self::EXAMPLE_COLUMN_NINE => 'Value To Constrain',                       // self::EXAMPLE_COLUMN_NINE AND           
    *              'Defaults to boolean AND grouping' => 'Nesting array switches to OR',    // ''='' AND 
    *              [
    *                  'Column Name' => 'Value To Constrain',                                  // ''='' OR
    *                  'This array is OR'ed together' => 'Another sud array would `AND`'       // ''=''
    *                  [ etc... ]
    *              ],
    *              'last' => 'whereExample'                                                  // AND '' = ''
    *        ],
    *        Rest::JOIN => [
    *            Rest::INNER => [
    *                Carbon_Users::CLASS_NAME => [
    *                    'Column Name' => 'Value To Constrain',
    *                    'Defaults to AND' => 'Nesting array switches to OR',
    *                    [
    *                       'Column Name' => 'Value To Constrain',
    *                       'This array is OR'ed together' => 'value'
    *                       [ 'Another sud array would `AND`ed... ]
    *                    ],
    *                    [ 'Column Name', Rest::LESS_THAN, 'Another Column Name']           // NOTE the Rest::LESS_THAN
    *                ]
    *            ],
    *            Rest::LEFT_OUTER => [
    *                Example_Table::CLASS_NAME => [
    *                    Location::USER_ID => Users::ID,
    *                    Location_References::ENTITY_KEY => $custom_var,
    *                   
    *                ],
    *                Example_Table_Two::CLASS_NAME => [
    *                    Example_Table_Two::ID => Example_Table_Two::subSelect($primary, $argv, $as, $pdo, $database)
    *                    ect... 
    *                ]
    *            ]
    *        ],
    *        Rest::PAGINATION => [
    *              Rest::PAGE => (int) 0, // used for pagination which equates to 
    *                  // ... LIMIT ' . (($argv[self::PAGINATION][self::PAGE] - 1) * $argv[self::PAGINATION][self::LIMIT]) 
    *                  //       . ',' . $argv[self::PAGINATION][self::LIMIT];
    *              
    *              Rest::LIMIT => (int) 90, // The maximum number of rows to return,
    *                       setting the limit explicitly to 1 will return a key pair array of only the
    *                       singular result. SETTING THE LIMIT TO NULL WILL ALLOW INFINITE RESULTS (NO LIMIT).
    *                       The limit defaults to 100 by design.
    *
    *               Rest::ORDER => [self::EXAMPLE_COLUMN_TEN => Rest::ASC ],  // i.e.  'username' => Rest::DESC
    *         ],
    *   ];
    *
    *
    * @param array $return
    * @param string|null $primary
    * @param array $argv
    * @noinspection DuplicatedCode - possible as this is generated
    * @generated
    * @throws PublicAlert|PDOException|JsonException
    * @return bool
    */
    public static function Get(array &$return, string $primary = null, array $argv = []): bool
    {
        self::startRest(self::GET, $return, $argv ,$primary);

        $pdo = self::database();

        $sql = self::buildSelectQuery($primary, $argv, '', $pdo);
        
        self::jsonSQLReporting(func_get_args(), $sql);
        
        self::postpreprocessRestRequest($sql);
        
        $stmt = $pdo->prepare($sql);

        self::bind($stmt);

        if (!$stmt->execute()) {
            self::completeRest();
            return self::signalError('The REST generated PDOStatement failed to execute with error :: ' . json_encode($stmt->errorInfo(), JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT));
        }

        $return = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        if ((null !== $primary && '' !== $primary) || (isset($argv[self::PAGINATION][self::LIMIT]) && $argv[self::PAGINATION][self::LIMIT] === 1 && count($return) === 1)) {
            $return = isset($return[0]) && is_array($return[0]) ? $return[0] : $return;
        }

        self::postprocessRestRequest($return);
        
        self::completeRest();
        
        return true;
    }

    /**
     * @param array $data 
     * @return bool|string|mixed
     * @generated
     * @throws PublicAlert|PDOException|JsonException
     */
    public static function Post(array $data = [])
    {   
        self::startRest(self::POST, [], $data);
    
        foreach ($data as $columnName => $postValue) {
            if (!array_key_exists($columnName, self::PDO_VALIDATION)) {
                return self::signalError("Restful table could not post column $columnName, because it does not appear to exist.");
            }
        } 
        
        $sql = 'INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES ( :post_author, :post_date, :post_date_gmt, :post_content, :post_title, :post_excerpt, :post_status, :comment_status, :ping_status, :post_password, :post_name, :to_ping, :pinged, :post_modified, :post_modified_gmt, :post_content_filtered, :post_parent, :guid, :menu_order, :post_type, :post_mime_type, :comment_count)';

        $pdo = self::database();
        
        if (!$pdo->inTransaction()) {
            $pdo->beginTransaction();
        }

        self::jsonSQLReporting(func_get_args(), $sql);

        self::postpreprocessRestRequest($sql);

        $stmt = self::database()->prepare($sql);
                 
        $post_author = $data['wp_posts.post_author'] ?? '0';
        $ref='wp_posts.post_author';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_author, $post_author === '0')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_author\'.');
        }
        $stmt->bindValue(':post_author', $post_author, PDO::PARAM_INT);
                 
        $post_date = $data['wp_posts.post_date'] ?? '0000-00-00 00:00:00';
        $ref='wp_posts.post_date';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_date, $post_date === '0000-00-00 00:00:00')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_date\'.');
        }
        $stmt->bindValue(':post_date', $post_date, PDO::PARAM_STR);
                 
        $post_date_gmt = $data['wp_posts.post_date_gmt'] ?? '0000-00-00 00:00:00';
        $ref='wp_posts.post_date_gmt';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_date_gmt, $post_date_gmt === '0000-00-00 00:00:00')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_date_gmt\'.');
        }
        $stmt->bindValue(':post_date_gmt', $post_date_gmt, PDO::PARAM_STR);
        
        if (!array_key_exists('wp_posts.post_content', $data)) {
            return self::signalError('The column \'wp_posts.post_content\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.post_content';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['post_content'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_content\'.');
        }
        $stmt->bindValue(':post_content', $data['wp_posts.post_content'], PDO::PARAM_STR);
        
        if (!array_key_exists('wp_posts.post_title', $data)) {
            return self::signalError('The column \'wp_posts.post_title\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.post_title';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['post_title'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_title\'.');
        }
        $stmt->bindValue(':post_title', $data['wp_posts.post_title'], PDO::PARAM_STR);
        
        if (!array_key_exists('wp_posts.post_excerpt', $data)) {
            return self::signalError('The column \'wp_posts.post_excerpt\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.post_excerpt';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['post_excerpt'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_excerpt\'.');
        }
        $stmt->bindValue(':post_excerpt', $data['wp_posts.post_excerpt'], PDO::PARAM_STR);
        
        $post_status = $data['wp_posts.post_status'] ?? 'publish';
        $ref='wp_posts.post_status';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_status, $post_status === 'publish')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_status\'.');
        }
        $stmt->bindParam(':post_status',$post_status, PDO::PARAM_STR, 20);
        
        $comment_status = $data['wp_posts.comment_status'] ?? 'open';
        $ref='wp_posts.comment_status';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $comment_status, $comment_status === 'open')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.comment_status\'.');
        }
        $stmt->bindParam(':comment_status',$comment_status, PDO::PARAM_STR, 20);
        
        $ping_status = $data['wp_posts.ping_status'] ?? 'open';
        $ref='wp_posts.ping_status';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $ping_status, $ping_status === 'open')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.ping_status\'.');
        }
        $stmt->bindParam(':ping_status',$ping_status, PDO::PARAM_STR, 20);
        
        $post_password = $data['wp_posts.post_password'] ?? '';
        $ref='wp_posts.post_password';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_password, $post_password === '')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_password\'.');
        }
        $stmt->bindParam(':post_password',$post_password, PDO::PARAM_STR, 255);
        
        $post_name = $data['wp_posts.post_name'] ?? '';
        $ref='wp_posts.post_name';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_name, $post_name === '')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_name\'.');
        }
        $stmt->bindParam(':post_name',$post_name, PDO::PARAM_STR, 200);
        
        if (!array_key_exists('wp_posts.to_ping', $data)) {
            return self::signalError('The column \'wp_posts.to_ping\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.to_ping';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['to_ping'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.to_ping\'.');
        }
        $stmt->bindValue(':to_ping', $data['wp_posts.to_ping'], PDO::PARAM_STR);
        
        if (!array_key_exists('wp_posts.pinged', $data)) {
            return self::signalError('The column \'wp_posts.pinged\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.pinged';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['pinged'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.pinged\'.');
        }
        $stmt->bindValue(':pinged', $data['wp_posts.pinged'], PDO::PARAM_STR);
                 
        $post_modified = $data['wp_posts.post_modified'] ?? '0000-00-00 00:00:00';
        $ref='wp_posts.post_modified';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_modified, $post_modified === '0000-00-00 00:00:00')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_modified\'.');
        }
        $stmt->bindValue(':post_modified', $post_modified, PDO::PARAM_STR);
                 
        $post_modified_gmt = $data['wp_posts.post_modified_gmt'] ?? '0000-00-00 00:00:00';
        $ref='wp_posts.post_modified_gmt';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_modified_gmt, $post_modified_gmt === '0000-00-00 00:00:00')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_modified_gmt\'.');
        }
        $stmt->bindValue(':post_modified_gmt', $post_modified_gmt, PDO::PARAM_STR);
        
        if (!array_key_exists('wp_posts.post_content_filtered', $data)) {
            return self::signalError('The column \'wp_posts.post_content_filtered\' is set to not null and has no default value. It must exist in the request and was not found in the one sent.');
        } 
        $ref='wp_posts.post_content_filtered';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $data['post_content_filtered'])) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_content_filtered\'.');
        }
        $stmt->bindValue(':post_content_filtered', $data['wp_posts.post_content_filtered'], PDO::PARAM_STR);
                 
        $post_parent = $data['wp_posts.post_parent'] ?? '0';
        $ref='wp_posts.post_parent';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_parent, $post_parent === '0')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_parent\'.');
        }
        $stmt->bindValue(':post_parent', $post_parent, PDO::PARAM_INT);
        
        $guid = $data['wp_posts.guid'] ?? '';
        $ref='wp_posts.guid';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $guid, $guid === '')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.guid\'.');
        }
        $stmt->bindParam(':guid',$guid, PDO::PARAM_STR, 255);
                 
        $menu_order = $data['wp_posts.menu_order'] ?? '0';
        $ref='wp_posts.menu_order';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $menu_order, $menu_order === '0')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.menu_order\'.');
        }
        $stmt->bindValue(':menu_order', $menu_order, PDO::PARAM_INT);
        
        $post_type = $data['wp_posts.post_type'] ?? 'post';
        $ref='wp_posts.post_type';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_type, $post_type === 'post')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_type\'.');
        }
        $stmt->bindParam(':post_type',$post_type, PDO::PARAM_STR, 20);
        
        $post_mime_type = $data['wp_posts.post_mime_type'] ?? '';
        $ref='wp_posts.post_mime_type';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $post_mime_type, $post_mime_type === '')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.post_mime_type\'.');
        }
        $stmt->bindParam(':post_mime_type',$post_mime_type, PDO::PARAM_STR, 100);
                 
        $comment_count = $data['wp_posts.comment_count'] ?? '0';
        $ref='wp_posts.comment_count';
        $op = self::EQUAL;
        if (!self::validateInternalColumn(self::POST, $ref, $op, $comment_count, $comment_count === '0')) {
            return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.comment_count\'.');
        }
        $stmt->bindValue(':comment_count', $comment_count, PDO::PARAM_INT);
        
        if (!$stmt->execute()) {
            self::completeRest();
            return self::signalError('The REST generated PDOStatement failed to execute with error :: ' . json_encode($stmt->errorInfo(), JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT));
        }
        
        $id = $pdo->lastInsertId();
        
        self::prepostprocessRestRequest($id);
        
        if (self::$commit && !Database::commit()) {
            return self::signalError('Failed to store commit transaction on table wp_posts');
        }
        
        self::postprocessRestRequest($id);
        
        self::completeRest();
        
        return $id;  
    }
    
    /**
    * 
    * 
    * Tables where primary keys exist must be updated by its primary key. 
    * Column should be in a key value pair passed to $argv or optionally using syntax:
    * $argv = [
    *       Rest::UPDATE => [
    *              ...
    *       ]
    * ]
    * 
    * @param array $returnUpdated - will be merged with with array_merge, with a successful update. 
    * @param string|null $primary
    * @param array $argv 
    * @generated
    * @throws PublicAlert|PDOException|JsonException
    * @return bool - if execute fails, false will be returned and $returnUpdated = $stmt->errorInfo(); 
    */
    public static function Put(array &$returnUpdated, string $primary = null, array $argv = []) : bool
    {
        self::startRest(self::PUT, $returnUpdated, $argv, $primary);
        
        $where = [];

        if (array_key_exists(self::WHERE, $argv)) {
            $where = $argv[self::WHERE];
            unset($argv[self::WHERE]);
        }
        
        if (array_key_exists(self::UPDATE, $argv)) {
            $argv = $argv[self::UPDATE];
        }
        
        $emptyPrimary = null === $primary || '' === $primary;
        
        if (false === self::$allowFullTableUpdates && $emptyPrimary) { 
            return self::signalError('Restful tables which have a primary key must be updated by its primary key. To bypass this set you may set `self::$allowFullTableUpdates = true;` during the PREPROCESS events.');
        }

        if (!$emptyPrimary) {
            $where[self::PRIMARY] = $primary;
        }
        
        foreach ($argv as $key => &$value) {
            if (!array_key_exists($key, self::PDO_VALIDATION)){
                return self::signalError('Restful table could not update column $key, because it does not appear to exist. Please re-run RestBuilder if you beleive this is incorrect.');
            }
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $key, $op, $value)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'wp_posts.\'.');
            }
        }
        unset($value);

        $sql = /** @lang MySQLFragment */ 'UPDATE wp_posts SET '; // intellij cant handle this otherwise

        $set = '';

        if (array_key_exists('wp_posts.ID', $argv)) {
            $set .= 'ID=:ID,';
        }
        if (array_key_exists('wp_posts.post_author', $argv)) {
            $set .= 'post_author=:post_author,';
        }
        if (array_key_exists('wp_posts.post_date', $argv)) {
            $set .= 'post_date=:post_date,';
        }
        if (array_key_exists('wp_posts.post_date_gmt', $argv)) {
            $set .= 'post_date_gmt=:post_date_gmt,';
        }
        if (array_key_exists('wp_posts.post_content', $argv)) {
            $set .= 'post_content=:post_content,';
        }
        if (array_key_exists('wp_posts.post_title', $argv)) {
            $set .= 'post_title=:post_title,';
        }
        if (array_key_exists('wp_posts.post_excerpt', $argv)) {
            $set .= 'post_excerpt=:post_excerpt,';
        }
        if (array_key_exists('wp_posts.post_status', $argv)) {
            $set .= 'post_status=:post_status,';
        }
        if (array_key_exists('wp_posts.comment_status', $argv)) {
            $set .= 'comment_status=:comment_status,';
        }
        if (array_key_exists('wp_posts.ping_status', $argv)) {
            $set .= 'ping_status=:ping_status,';
        }
        if (array_key_exists('wp_posts.post_password', $argv)) {
            $set .= 'post_password=:post_password,';
        }
        if (array_key_exists('wp_posts.post_name', $argv)) {
            $set .= 'post_name=:post_name,';
        }
        if (array_key_exists('wp_posts.to_ping', $argv)) {
            $set .= 'to_ping=:to_ping,';
        }
        if (array_key_exists('wp_posts.pinged', $argv)) {
            $set .= 'pinged=:pinged,';
        }
        if (array_key_exists('wp_posts.post_modified', $argv)) {
            $set .= 'post_modified=:post_modified,';
        }
        if (array_key_exists('wp_posts.post_modified_gmt', $argv)) {
            $set .= 'post_modified_gmt=:post_modified_gmt,';
        }
        if (array_key_exists('wp_posts.post_content_filtered', $argv)) {
            $set .= 'post_content_filtered=:post_content_filtered,';
        }
        if (array_key_exists('wp_posts.post_parent', $argv)) {
            $set .= 'post_parent=:post_parent,';
        }
        if (array_key_exists('wp_posts.guid', $argv)) {
            $set .= 'guid=:guid,';
        }
        if (array_key_exists('wp_posts.menu_order', $argv)) {
            $set .= 'menu_order=:menu_order,';
        }
        if (array_key_exists('wp_posts.post_type', $argv)) {
            $set .= 'post_type=:post_type,';
        }
        if (array_key_exists('wp_posts.post_mime_type', $argv)) {
            $set .= 'post_mime_type=:post_mime_type,';
        }
        if (array_key_exists('wp_posts.comment_count', $argv)) {
            $set .= 'comment_count=:comment_count,';
        }
        
        $sql .= substr($set, 0, -1);

        $pdo = self::database();
        
        if (!$pdo->inTransaction()) {
            $pdo->beginTransaction();
        }

        if (false === self::$allowFullTableUpdates || !empty($where)) {
            $sql .= ' WHERE ' . self::buildBooleanJoinConditions(self::PUT, $where, $pdo);
        }
        
        self::jsonSQLReporting(func_get_args(), $sql);

        self::postpreprocessRestRequest($sql);

        $stmt = $pdo->prepare($sql);

        if (array_key_exists('wp_posts.ID', $argv)) { 
            $stmt->bindValue(':ID',$argv['wp_posts.ID'], PDO::PARAM_INT);
        }
        if (array_key_exists('wp_posts.post_author', $argv)) { 
            $stmt->bindValue(':post_author',$argv['wp_posts.post_author'], PDO::PARAM_INT);
        }
        if (array_key_exists('wp_posts.post_date', $argv)) { 
            $stmt->bindValue(':post_date',$argv['wp_posts.post_date'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_date_gmt', $argv)) { 
            $stmt->bindValue(':post_date_gmt',$argv['wp_posts.post_date_gmt'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_content', $argv)) { 
            $stmt->bindValue(':post_content',$argv['wp_posts.post_content'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_title', $argv)) { 
            $stmt->bindValue(':post_title',$argv['wp_posts.post_title'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_excerpt', $argv)) { 
            $stmt->bindValue(':post_excerpt',$argv['wp_posts.post_excerpt'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_status', $argv)) { 
            $post_status = $argv['wp_posts.post_status'];
            $ref = 'wp_posts.post_status';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $post_status)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'post_status\'.');
            }
            $stmt->bindParam(':post_status',$post_status, PDO::PARAM_STR, 20);
        }
        if (array_key_exists('wp_posts.comment_status', $argv)) { 
            $comment_status = $argv['wp_posts.comment_status'];
            $ref = 'wp_posts.comment_status';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $comment_status)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'comment_status\'.');
            }
            $stmt->bindParam(':comment_status',$comment_status, PDO::PARAM_STR, 20);
        }
        if (array_key_exists('wp_posts.ping_status', $argv)) { 
            $ping_status = $argv['wp_posts.ping_status'];
            $ref = 'wp_posts.ping_status';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $ping_status)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'ping_status\'.');
            }
            $stmt->bindParam(':ping_status',$ping_status, PDO::PARAM_STR, 20);
        }
        if (array_key_exists('wp_posts.post_password', $argv)) { 
            $post_password = $argv['wp_posts.post_password'];
            $ref = 'wp_posts.post_password';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $post_password)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'post_password\'.');
            }
            $stmt->bindParam(':post_password',$post_password, PDO::PARAM_STR, 255);
        }
        if (array_key_exists('wp_posts.post_name', $argv)) { 
            $post_name = $argv['wp_posts.post_name'];
            $ref = 'wp_posts.post_name';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $post_name)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'post_name\'.');
            }
            $stmt->bindParam(':post_name',$post_name, PDO::PARAM_STR, 200);
        }
        if (array_key_exists('wp_posts.to_ping', $argv)) { 
            $stmt->bindValue(':to_ping',$argv['wp_posts.to_ping'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.pinged', $argv)) { 
            $stmt->bindValue(':pinged',$argv['wp_posts.pinged'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_modified', $argv)) { 
            $stmt->bindValue(':post_modified',$argv['wp_posts.post_modified'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_modified_gmt', $argv)) { 
            $stmt->bindValue(':post_modified_gmt',$argv['wp_posts.post_modified_gmt'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_content_filtered', $argv)) { 
            $stmt->bindValue(':post_content_filtered',$argv['wp_posts.post_content_filtered'], PDO::PARAM_STR);
        }
        if (array_key_exists('wp_posts.post_parent', $argv)) { 
            $stmt->bindValue(':post_parent',$argv['wp_posts.post_parent'], PDO::PARAM_INT);
        }
        if (array_key_exists('wp_posts.guid', $argv)) { 
            $guid = $argv['wp_posts.guid'];
            $ref = 'wp_posts.guid';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $guid)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'guid\'.');
            }
            $stmt->bindParam(':guid',$guid, PDO::PARAM_STR, 255);
        }
        if (array_key_exists('wp_posts.menu_order', $argv)) { 
            $stmt->bindValue(':menu_order',$argv['wp_posts.menu_order'], PDO::PARAM_INT);
        }
        if (array_key_exists('wp_posts.post_type', $argv)) { 
            $post_type = $argv['wp_posts.post_type'];
            $ref = 'wp_posts.post_type';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $post_type)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'post_type\'.');
            }
            $stmt->bindParam(':post_type',$post_type, PDO::PARAM_STR, 20);
        }
        if (array_key_exists('wp_posts.post_mime_type', $argv)) { 
            $post_mime_type = $argv['wp_posts.post_mime_type'];
            $ref = 'wp_posts.post_mime_type';
            $op = self::EQUAL;
            if (!self::validateInternalColumn(self::PUT, $ref, $op, $post_mime_type)) {
                return self::signalError('Your custom restful api validations caused the request to fail on column \'post_mime_type\'.');
            }
            $stmt->bindParam(':post_mime_type',$post_mime_type, PDO::PARAM_STR, 100);
        }
        if (array_key_exists('wp_posts.comment_count', $argv)) { 
            $stmt->bindValue(':comment_count',$argv['wp_posts.comment_count'], PDO::PARAM_INT);
        }
        
        self::bind($stmt);

        if (!$stmt->execute()) {
            self::completeRest();
            return self::signalError('The REST generated PDOStatement failed to execute with error :: ' . json_encode($stmt->errorInfo(), JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT));
        }
        
        if (!$stmt->rowCount()) {
            return self::signalError('Failed to find the target row.');
        }
        
        $argv = array_combine(
            array_map(
                static fn($k) => str_replace('wp_posts.', '', $k),
                array_keys($argv)
            ),
            array_values($argv)
        );

        $returnUpdated = array_merge($returnUpdated, $argv);
        
        self::prepostprocessRestRequest($returnUpdated);
        
        if (self::$commit && !Database::commit()) {
            return self::signalError('Failed to store commit transaction on table wp_posts');
        }
        
        self::postprocessRestRequest($returnUpdated);
        
        self::completeRest();
        
        return true;
    }

    /**
    * @param array $remove
    * @param string|null $primary
    * @param array $argv
    * @generated
    * @noinspection DuplicatedCode
    * @throws PublicAlert|PDOException|JsonException
    * @return bool
    */
    public static function Delete(array &$remove, string $primary = null, array $argv = []) : bool
    {
        self::startRest(self::DELETE, $remove, $argv, $primary);
        
        $pdo = self::database();
        
        $emptyPrimary = null === $primary || '' === $primary;
        
        $sql =  /** @lang MySQLFragment */ 'DELETE FROM wp_posts ';
        
        if (false === self::$allowFullTableDeletes && $emptyPrimary && empty($argv)) {
            return self::signalError('When deleting from restful tables a primary key or where query must be provided. This can be disabled by setting `self::$allowFullTableUpdates = true;` during the PREPROCESS events, or just directly before this request.');
        }
        
        if (!$emptyPrimary) {
            $argv[self::PRIMARY] = $primary;
        }
        
        $where = self::buildBooleanJoinConditions(self::DELETE, $argv, $pdo);
        
        $emptyWhere = empty($where);
        
        if ($emptyWhere && false === self::$allowFullTableDeletes) {
            return self::signalError('The where condition provided appears invalid.');
        }

        if (!$emptyWhere) {
            $sql .= ' WHERE ' . $where;
        }
        
        if (!$pdo->inTransaction()) {
            $pdo->beginTransaction();
        }
        
        self::jsonSQLReporting(func_get_args(), $sql);

        self::postpreprocessRestRequest($sql);

        $stmt = $pdo->prepare($sql);

        self::bind($stmt);

        if (!$stmt->execute()) {
            self::completeRest();
            return self::signalError('The REST generated PDOStatement failed to execute with error :: ' . json_encode($stmt->errorInfo(), JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT));
        }

        $remove = [];
        
        self::prepostprocessRestRequest($remove);
        
        if (self::$commit && !Database::commit()) {
           return self::signalError('Failed to store commit transaction on table wp_posts');
        }
        
        self::postprocessRestRequest($remove);
        
        self::completeRest();
        
        return true;
    }
}
