name: CarbonPHP Feature Test Suit

on: [ push ]

jobs:
  Linux:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{matrix.operating-system}}
    container: ${{matrix.container}}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: php-cs-fixer, phpunit
        env:
          update: true # specify true or false

      - name: service  --status-all
        run: service  --status-all

      - name: sudo systemctl start mysql.service
        run: sudo systemctl start mysql.service

      - name: echo -e "[client]\n user=root \n password=root \n host=localhost" > `pwd`/mysql.cnf
        run: echo -e "[client]\n user=root \n password=root \n host=localhost" > `pwd`/mysql.cnf

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e "create database \`CarbonPHP\`"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e "create database \`CarbonPHP\`"

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "GRANT ALL PRIVILEGES ON CarbonPHP. * TO 'root'@'localhost';"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "GRANT ALL PRIVILEGES ON CarbonPHP. * TO 'root'@'localhost';"

      - name: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"
        run: mysql --defaults-extra-file="`pwd`/mysql.cnf" -e  "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"

      - name: sudo update-alternatives --set php /usr/bin/php7.4
        run: sudo update-alternatives --set php /usr/bin/php7.4

      - name: composer validate
        run: composer validate

      - name: composer wordpress:download:latest-stable
        run: composer wordpress:download:latest-stable

      - name: composer install --prefer-dist --no-progress --no-suggest
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: php index.php buildDatabase -r
        run: php index.php buildDatabase -r

      - name: php index.php rest
        run: php index.php rest

      - name: php index.php rest  (again to ensure generated php valid)
        run: php index.php rest

      - name: ./vendor/se/selenium-server-standalone/composer/bin/selenium-server-standalone &
        run: ./vendor/se/selenium-server-standalone/composer/bin/selenium-server-standalone &

        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md
      - name: Run test suite
        run: composer run test
